# .rubocop.yml

Metrics/AbcSize:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Layout/LineLength:
  Max: 140
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - spec/**/*
